# This is a basic workflow to help you get started with Actions

name: Sun or Sunlight


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: chưa xác định
  pull_request: 
    branches: chưa có

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: Dùng phần mềm 4D đưa con người vào thế giới trong game để cảm nhận

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: nhiều công việc cùng một lúc 
  # This workflow contains a single job called "build"
  build: Xây dựng bang hội phát triển nơi ở, xây dựng nhà dân và ruộng 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
